### ISSUE TITLE
open-helpdesk broken by django and django-contrib-comments

### ISSUE THREAD

**Issue by NeolithEra** [simodalla/open-helpdesk#4]
Hi, users are unable to run **_open-helpdesk_** due to dependency conflict with _**django**_ package. 
As shown in the following full dependency graph of **_open-helpdesk_**, **_open-helpdesk_** requires _**django>=1.10.8,<1.11.0**_，while **_django-contrib-comments_** requires _**Django>=1.11**_.

According to pip’s “first found wins” installation strategy, _**Django 1.10.8**_ is the actually installed version. However, _**Django 1.10.8**_ does not satisfy _**Django>=1.11**_.

### Dependency tree
```
open-helpdesk-v_0.9.9
| +-celery(version range:==4.0.2)
| +-django(version range:==1.10.6)
| +-django-autocomplete-light(version range:==3.0.4)
| +-django-braces(version range:==1.10.0)
| +-django-celery-email(version range:==1.1.5)
| | +-celery(version range:>=2.3.0)
| | +-django(version range:>=1.7)
| | +-django-appconf(version range:*)
| | | +-django(version range:*)
| | | +-six(version range:*)
| +-django-model-utils(version range:==2.6.1)
| | +-django(version range:>=1.4.2)
| +-django-tinymce(version range:==2.4.0)
| +-django-waffle(version range:==0.11)
| +-mezzanine(version range:==4.2.2)
| | +-beautifulsoup4(version range:>=4.1.3)
| | | +-soupsieve(version range:>=1.2)
| | +-bleach(version range:>=1.4)
| | | +-six(version range:>=1.9.0)
| | | +-webencodings(version range:*)
| | +-chardet(version range:*)
| | +-django(version range:<1.11,>=1.8)
| | +-django-contrib-comments(version range:*)
| | | +-django(version range:>=1.11)
| | +-filebrowser-safe(version range:>=0.4.6)
| | +-future(version range:>=0.9.0)
| | +-grappelli-safe(version range:>=0.4.5)
| | +-pillow(version range:*)
| | +-requests(version range:>=2.1.0)
| | | +-certifi(version range:>=2017.4.17)
| | | +-chardet(version range:<3.1.0,>=3.0.2)
| | | +-idna(version range:>=2.5,<2.9)
| | | +-urllib3(version range:<1.26,>=1.21.1)
| | +-requests-oauthlib(version range:>=0.4)
| | +-tzlocal(version range:>=1.0)
| | | +-pytz(version range:*)
| +-psycopg2(version range:==2.6.2)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Solution

Add django-contrib-comments==1.8.0 as a direct dependency.
As django-contrib-comments==1.8.0 requires Django>=1.8, then this conflict can be removed.

@simodalla May I submit a PR to solve this issue?

**Comment by simodalla** [comment]
Hi @NeolithEra,
sure, you can submit PR for this issue.
Thank you.

**Comment by simodalla** [comment]
Hi @NeolithEra,
i've merged your PR. If you want add yourself into AUTHORS.rst as contributor.
Thank you.
Simone
